In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import seaborn as sns

The following data is from NYS Open data and lists active corporations since 1800. Full documentation can be found here: https://dev.socrata.com/foundry/data.ny.gov/vz7i-btsq

In [2]:
corps = pd.read_json ('https://data.ny.gov/resource/vz7i-btsq.json')

In [3]:
corps.head()

,chairman_address_1,chairman_address_2,chairman_city,chairman_name,chairman_state,chairman_zip,county,current_entity_name,dos_id,dos_process_address_1,...,location_city,location_name,location_state,location_zip,registered_agent_address_1,registered_agent_address_2,registered_agent_city,registered_agent_name,registered_agent_state,registered_agent_zip
0,NaN,NaN,NaN,NaN,NaN,NaN,KINGS,00:02:59 LLC,3211809,"656 UNION STREET, APT. 2",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,KINGS,000 LLC,4472700,304 MESEROLE ST #2A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,SUFFOLK,"000 MEADOW LANE, LLC",4723823,34 PANTIGO ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,SUFFOLK,00168 HOME CORP.,5224240,28 PHEASANT RUN LANE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,"002 MERCURY TACOS, LLC",4610986,131 7TH AVE S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
corps.describe()

             dos_id
count  1.000000e+03
mean   3.845011e+06
std    1.248298e+06
min    1.178600e+04
25%    3.123032e+06
50%    4.195544e+06
75%    4.838516e+06
max    5.349008e+06

In [5]:
corps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 30 columns):
chairman_address_1            98 non-null object
chairman_address_2            23 non-null object
chairman_city                 98 non-null object
chairman_name                 98 non-null object
chairman_state                98 non-null object
chairman_zip                  98 non-null object
county                        999 non-null object
current_entity_name           1000 non-null object
dos_id                        1000 non-null int64
dos_process_address_1         992 non-null object
dos_process_address_2         210 non-null object
dos_process_city              992 non-null object
dos_process_name              992 non-null object
dos_process_state             992 non-null object
dos_process_zip               990 non-null object
entity_type                   1000 non-null object
initial_dos_filing_date       1000 non-null object
jurisdiction                  1000 non-null object
location_address_1            99 non-null object
location_address_2            22 non-null object
location_city                 99 non-null object
location_name                 99 non-null object
location_state                99 non-null object
location_zip                  99 non-null object
registered_agent_address_1    101 non-null object
registered_agent_address_2    16 non-null object
registered_agent_city         101 non-null object
registered_agent_name         108 non-null object
registered_agent_state        101 non-null object
registered_agent_zip          101 non-null object
dtypes: int64(1), object(29)
memory usage: 234.5+ KB

So here I would want to figure out what to do given the wide variation in NULLs across columns.

In [6]:
city_group = corps.groupby('location_city')

In [7]:
print(city_group)

<pandas.core.groupby.groupby.DataFrameGroupBy object at 0x1a189c4358>

In [8]:
city_group.head()

,chairman_address_1,chairman_address_2,chairman_city,chairman_name,chairman_state,chairman_zip,county,current_entity_name,dos_id,dos_process_address_1,...,location_city,location_name,location_state,location_zip,registered_agent_address_1,registered_agent_address_2,registered_agent_city,registered_agent_name,registered_agent_state,registered_agent_zip
0,NaN,NaN,NaN,NaN,NaN,NaN,KINGS,00:02:59 LLC,3211809,"656 UNION STREET, APT. 2",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,KINGS,000 LLC,4472700,304 MESEROLE ST #2A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,SUFFOLK,"000 MEADOW LANE, LLC",4723823,34 PANTIGO ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,SUFFOLK,00168 HOME CORP.,5224240,28 PHEASANT RUN LANE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,"002 MERCURY TACOS, LLC",4610986,131 7TH AVE S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10 RED OAK DRIVE,NaN,SCOTIA,RICHARD P. SZMYR,NEW YORK,12302,SCHENECTADY,"007 ELECTRONICS NETWORK, INC.",2067108,10 RED OAK DRIVE,...,SCOTIA,RICHARD P. SZMYR,NEW YORK,12302,NaN,NaN,NaN,NaN,NaN,NaN
25,63 SKILLMAN AVENUE APT 1,NaN,BROOKLYN,BENEDETTA AMADI,NEW YORK,11211,NEW YORK,010COMMUNICATIONS INC.,3785280,"63 SKILLMAN AVENUE, SUITE #1",...,BROOKLYN,010COMMUNICATIONS INC,NEW YORK,11211,NaN,NaN,NaN,NaN,NaN,NaN
33,61-20 185TH ST,#2,FRESH MEADOWS,ALLAN CHEMTOB,NEW YORK,11365,NEW YORK,011 SERVICES CORP.,4154481,61-20 185TH ST,...,FRESH MEADOWS,011 SERVICES CORP.,NEW YORK,11365,1 MAIDEN LANE 5TH FLOOR,NaN,NEW YORK,"SPIEGEL & UTRERA, P.A., P.C.",NEW YORK,10038
34,200 S SERVICE RD,STE 211,ROSLYN HEIGHTS,PARMOD KUMAR,NEW YORK,11577,QUEENS,011 TELECOM INC.,2664830,200 S SERVICE RD,...,ROSLYN HEIGHTS,PARMOD KUMAR,NEW YORK,11577,NaN,NaN,NaN,NaN,NaN,NaN
51,812 58TH ST,NaN,BROOKLYN,FANG LIN,NEW YORK,11220,KINGS,02 BEAUTY CENTER INC,3635057,812 58TH STREET,...,BROOKLYN,02 BEAUTY CENTER INC,NEW YORK,11220,NaN,NaN,NaN,NaN,NaN,NaN
59,28 OLD STONE HILL RD,NaN,POUND RIDGE,FRANK O'NEILL,NEW YORK,10576-1515,WESTCHESTER,02 STRATEGIES INC.,1719211,28 OLD STONE HILL RD,...,POUND RIDGE,02 STRATEGIES INC.,NEW YORK,10576-1515,NaN,NaN,NaN,NaN,NaN,NaN
61,2355 INDUSTRIAL PARK BLVD,NaN,CUMMING,RON BUKSHPAN,GEORGIA,30041,NEW YORK,"02WIRELESS SYSTEMS GROUP, INC.",2116899,2355 INDUSTRIAL PARK BLVD,...,CUMMING,RON RAVIV,GEORGIA,30041,111 EIGHTH AVENUE,NaN,NEW YORK,C T CORPORATION SYSTEM,NEW YORK,10011
74,45-55 162ND ST. 1 FL.,NaN,FLUSHING,CHARLES BAI,NEW YORK,11358,QUEENS,0404 MESSENGER SERVICE INC.,4189060,45-55 162ND ST. 1FL,...,FLUSHING,0404 MESSENGER SERVICE INC.,NEW YORK,11358,NaN,NaN,NaN,NaN,NaN,NaN
90,3718 NORTHERN BLVD,SUITE 417,LONG ISLAND CITY,MIRI ZOAREZ,NEW YORK,11101,NASSAU,060182 CORP.,4163990,100 MERRICK ROAD SUITE 400E,...,ROCKVILLE CENTRE,060182 CORP.,NEW YORK,11570,NaN,NaN,NaN,NaN,NaN,NaN
108,13 PALMEAR RD,NaN,FREEVILLE,DONALD E SCUTT,NEW YORK,13068,TOMPKINS,"0819, INC.",3547128,13 PALMEAR RD,...,FREEVILLE,"0819, INC.",NEW YORK,13068,NaN,NaN,NaN,NaN,NaN,NaN
117,311 EAST 23RD ST,STE 10AA,NEW YORK,PAUL R KAHANE,NEW YORK,10010-4741,NEW YORK,"094 ASSOCIATES, INC.",2776950,311 EAST 23RD STREET,...,NEW YORK,PAUL R KAHANE,NEW YORK,10010-4741,"45 JOHN STREET, SUITE 711",NaN,NEW YORK,"SPIEGEL & UTRERA, P.A., P.C.",NEW YORK,10038
120,107 JAY ST,NaN,FREEPORT,CATALINA SARAVIA,NEW YORK,11520,NASSAU,099 CENTS TOYS CORPORATION,4208221,86 NORTH FRANKLIN ST,...,HEMPSTEAD,099 CENTS TOYS CORPORATION,NEW YORK,11550,NaN,NaN,NaN,NaN,NaN,NaN
129,2 HICKORY DR.,NaN,RYE,JAMES J. DIDONATO,NEW YORK,10550,WESTCHESTER,0 EDISON AVENUE REALTY CORP.,2512637,80 EDISON AVE.,...,MT. VERNON,0 EDISON AVENUE REALTY CORP.,NEW YORK,10550,NaN,NaN,NaN,NaN,NaN,NaN
130,45 BANFI PLAZA N,NaN,FARMINGDALE,BRUCE R. THAW,NEW YORK,11735,SUFFOLK,"0ENERGY LIGHTING, INC.",4222927,111 EIGHTH AVENUE,...,FARMINGDALE,"0ENERGY LIGHTING, INC.",NEW YORK,11735,111 EIGHTH AVENUE,NaN,NEW YORK,C T CORPORATION SYSTEM,NEW YORK,10011
170,100-05 92ND AVE,NaN,RICHMOND HILL,JEFF ROSEN,NEW YORK,11418,QUEENS,100-02 92ND AVENUE REALTY INC.,1803570,100-05 92ND AVENUE,...,RICHMOND HILL,JEFF ROSEN,NEW YORK,11418,NaN,NaN,NaN,NaN,NaN,NaN
172,85 DICKENSON PL.,NaN,GREAT NECK,MANNY M. ALANI,NEW YORK,11023-1926,NEW YORK,100-02 NORTHERN BLVD. REALTY CORP.,1045005,85 DICKENSON PL.,...,GREAT NECK,MANNY M. ALANI,NEW YORK,11023-1926,NaN,NaN,NaN,NaN,NaN,NaN
183,30 SINCLAIR DRIVE,NaN,KINGS POINT,LUCI AZIZIAN,NEW YORK,11024,NASSAU,100-07 REALTY CORP.,3391009,30 SINCLAIR DRIVE,...,KINGS POINT,ISSAC AZIZIAN,NEW YORK,11024,NaN,NaN,NaN,NaN,NaN,NaN
187,117-07 95TH AVE,NaN,RICHMOND HILL,SIMRANJEET SINGH,NEW YORK,11419,QUEENS,100-08 HOLDING CORPORATION,4399026,100-08 101 AVE,...,RICHMOND HILL,100-08 HOLDING CORPORATION,NEW YORK,11419,NaN,NaN,NaN,NaN,NaN,NaN
195,465 WARRENSBURG RD,NaN,STONY CREEK,JACK AREHART,NEW YORK,12878,WARREN,"1000 ACRES RANCH RESORT, INC.",1100715,465 WARRENSBURG RD,...,STONY CREEK,"1000 ACRES RANCH RESORT, INC.",NEW YORK,12878,NaN,NaN,NaN,NaN,NaN,NaN
203,P. O. BOX 127,234 GENESEE STREET,CHITTENANGO,ROBERT J. BENSON,NEW YORK,13037,MADISON,"1000 BOLIVAR ROAD, INC.",3985227,P.O. BOX 127,...,CHITTENANGO,ROBERT J. BENSON,NEW YORK,13037,NaN,NaN,NaN,NaN,NaN,NaN
205,C/O MORRIS COMPANIES,350 VETERANS BLVD,RUTHERFORD,ROBERT MORRIS,NEW JERSEY,07070,NASSAU,1000 BRIDGE PLAZA SOUTH CORP.,66938,350 VETERANS BLVD.,...,RUTHERFORD,1000 BRIDGE PLAZA SOUTH CORP.,NEW JERSEY,07070,NaN,NaN,NaN,NaN,NaN,NaN
239,1000 HOWARD ROAD,NaN,ROCHESTER,EARL D. ZIELINSKI,NEW YORK,14624,MONROE,"1000 HOWARD ROAD, INC.",386049,1000 HOWARD ROAD,...,ROCHESTER,"1000 HOWARD ROAD, INC.",NEW YORK,14624,NaN,NaN,NaN,NaN,NaN,NaN
249,21207 COFFEEN ST.,NaN,WATERTOWN,BRUCE W. GRABLE,NEW YORK,13601,JEFFERSON,"1000 ISLANDS MOVING & STORAGE, INC.",2001227,21207 COFFEEN STREET,...,WATERTOWN,"1000 ISLANDS MOVING & STORAGE, INC.",NEW YORK,13601,NaN,NaN,NaN,NaN,NaN,NaN
253,17109 COUNTY RTE 3,NaN,CLAYTON,MARY C SCUDERA,NEW YORK,13624,JEFFERSON,"1000 ISLANDS RIVER RAT CHEESE, INC.",1947051,242 JAMES STREET,...,CLAYTON,"1000 ISLANDS RIVER RAT CHEESE, INC.",NEW YORK,13624,NaN,NaN,NaN,NaN,NaN,NaN
256,9 SISSON ST,NaN,ALEXANDRIA BAY,MICHAEL L. CHAVOUSTIE,NEW YORK,13607,JEFFERSON,1000 ISLANDS TRADITION INC.,1692930,22 SISSON ST,...,ALEXANDRIA BAY,MICHAEL L CHAVOUSTIE,NEW YORK,13607,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,817 ALLERTON AVE,NaN,BRONX,DOMENICO BROCCOLI,NEW YORK,10467,BRONX,1001 WHITE PLAINS ROAD RESTAURANT CORP.,4092530,817 ALLERTON AVE,...,BRONX,1001 WHITE PLAINS ROAD RESTAURANT CORP.,NEW YORK,10567,NaN,NaN,NaN,NaN,NaN,NaN
463,26-10 BROOKLYN QUEENS EXPY W,NaN,WOODSIDE,IRVING BORK,NEW YORK,11377,QUEENS,100-200 CORPORATE CENTER INC.,355348,26-10 BROOKLYN QUEENS EXPY W,...,WOODSIDE,IRVING BORK,NEW YORK,11377,NaN,NaN,NaN,NaN,NaN,NaN
477,107 RUSTIC RD,NaN,PORT JEFFERSON,KATHY L STANISLAW,NEW YORK,11777,SUFFOLK,100-24 JERSEY AVE. HOLDING CORP.,2995388,107 RUSTIC ROAD,...,PORT JEFFERSON,100-24 JERSEY AVE. HOLDING CORP.,NEW YORK,11777,NaN,NaN,NaN,NaN,NaN,NaN
482,25-83 FRANCIS LEWIS BLVD,NaN,BAYSIDE,MITCH HOCHHAUSER,NEW YORK,11358,QUEENS,"100-26 67TH OWNERS, INC.",933983,C/O GABRIEL MGMT,...,BAYSIDE,"100-26 67TH OWNERS, INC.",NEW YORK,11358,NaN,NaN,NaN,NaN,NaN,NaN
487,5002 EAST BROOK PL,NaN,CLARENCE,MOTASIM AGHA,NEW YORK,14221,ERIE,"1002 ABBOTT, INC.",3474891,1177 HERTEL AVENUE,...,WILLIAMSVILLE,MOTASIM AGHA,NEW YORK,14221,NaN,NaN,NaN,NaN,NaN,NaN
506,1002 ROSSVILLE AVE,NaN,STATEN ISLAND,LARRY SCHWARTZ,NEW YORK,10309,RICHMOND,1002 KARISS FRENCH CLEANERS CORP.,1601758,1002 ROSSVILLE AVENUE,...,STATEN ISLAND,1002 KARISS FRENCH CLEANERS CORP.,NEW YORK,10309,NaN,NaN,NaN,NaN,NaN,NaN
521,112 WALL STREET,NaN,TORRINGTON,KEN MERZ,CONNECTICUT,06790-5464,PUTNAM,1002 SOUTH MAIN CORPORATION,2571259,PO BOX 410 / FIELDS LANE,...,BREWSTER,1002 SOUTH MAIN CORPORATION,NEW YORK,10509,NaN,NaN,NaN,NaN,NaN,NaN
531,935 BRONX RIVR AVENUE,UPSTAIRS,BRONX,DOMINIC FERROVECCHIO,NEW YORK,10473,BRONX,"1003 ELDER AVENUE, INC.",3828428,935 BRONX RIVER AVENUE,...,BRONX,JOSE RODRIGUES JR,NEW YORK,10473,NaN,NaN,NaN,REGISTERED AGENT REVOKED,NaN,NaN
535,9890 STATE HWY 37,NaN,OGDENSBURG,SCHIEL S WOOD,NEW YORK,13669,ST. LAWRENCE,"1003 PARK STREET, INC.",1256092,1003 PARK STREET,...,OGDENSBURG,"1003 PARK STREET, INC.",NEW YORK,13669,NaN,NaN,NaN,NaN,NaN,NaN
541,1003 WALNUT STREET,NaN,ELMIRA,CAROLYN HODGES CHAFFEE,NEW YORK,14901,CHEMUNG,"1003 WALNUT STREET, INC.",3101753,1003 WALNUT STREET,...,ELMIRA,CAROLYN HODGES CHAFFEE,NEW YORK,14901,NaN,NaN,NaN,NaN,NaN,NaN
571,161-10 43RD AVE 3RD FLR,NaN,FLUSHING,SUNG KYUNG CHO,NEW YORK,11358,QUEENS,"1004 PREMIERE USA, INC.",3720627,161-10 43RD AVENUE,...,FLUSHING,"1004 PREMIERE USA, INC.",NEW YORK,11358,NaN,NaN,NaN,NaN,NaN,NaN
575,147 BARRET ST,NaN,SCHENECTADY,RICHARD G DELLA RATTA,NEW YORK,12305,SCHENECTADY,"1004 UNION STREET, INC.",3735707,NO. 147 BARRETT STREET,...,SCHENECTADY,RICHARD G DELLA RATTA,NEW YORK,12305,NaN,NaN,NaN,NaN,NaN,NaN
589,935 BRONX RIVER AVE,UPSTAIRS,BRONX,DOMINIC FERROVECCHIO,NEW YORK,10473,BRONX,"1005 ELDER AVENUE, INC.",3832674,114 KINGSBURY COURT,...,BRONX,"JOSE RODRIGUES, JR",NEW YORK,10473,NaN,NaN,NaN,REGISTERED AGENT REVOKED,NaN,NaN
596,2074 HARRIS RD,NaN,PENFIELD,CHRISTOPHER SCHEG,NEW YORK,14526,MONROE,"10-05, INC.",3630800,80 STATE STREET,...,PENFIELD,"10-05, INC.",NEW YORK,14526,80 STATE STREET,NaN,ALBANY,CORPORATION SERVICE COMPANY,NEW YORK,12207
600,5105 DUCK DOWN CT,NaN,RALEIGH,DOMENICK BARRESI,NORTH CAROLINA,27604,NASSAU,1005 JERUSALEM AVE. REALTY CO. INC.,920444,5105 DUCK DOWN CT,...,NORTH MERRICK,DOMENICK BARRESI,NEW YORK,11566,NaN,NaN,NaN,NaN,NaN,NaN
616,8080 EFFIE DRIVE,NaN,NIAGARA FALLS,ANDREA STRANGIO,NEW YORK,14304,NIAGARA,"10065 N.F. BLVD., INC.",3477685,8080 EFFIE DRIVE,...,NIAGARA FALLS,"10065 N.F. BLVD., INC.",NEW YORK,14304,NaN,NaN,NaN,NaN,NaN,NaN
648,4 HORIZON RD,NaN,FORT LEE,JOHN MORALES,NEW JERSEY,07024,BRONX,"1007 BOULEVARD SHOES, INC.",3916029,4 HORIZON RD,...,FORT LEE,JOHN MORALES,NEW JERSEY,07024,NaN,NaN,NaN,NaN,NaN,NaN
653,1007 HEMPSTEAD TURNPIKE,NaN,FRANKLIN SQUARE,JACK M FALZONE,NEW YORK,11010,NASSAU,1007 HEMPSTEAD TURNPIKE CORP.,2577760,"ATTN: KEVIN J. LAKE, ESQ.",...,FRANKLIN SQUARE,1007 HEMPSTEAD TURNPIKE CORP.,NEW YORK,11010,NaN,NaN,NaN,NaN,NaN,NaN
720,23 ANTONA BLVD,NaN,CENTEREACH,JOSEPH ARICO,NEW YORK,11720,SUFFOLK,100 ACRE WOOD DEVELOPMENT CORP.,2331187,23 ANTONA BLVD,...,CENTEREACH,100 ACRE WOOD DEVELOPMENT CORP.,NEW YORK,11720,NaN,NaN,NaN,NaN,NaN,NaN
732,199 MAIN STREET,4TH FLOOR,WHITE PLAINS,"STEPHEN J. LEHRMAN, PRESIDENT",NEW YORK,10601,WESTCHESTER,100 APARTMENT ASSOCIATES INC.,2317051,199 MAIN STREET,...,WHITE PLAINS,100 APARTMENT ASSOCIATES INC.,NEW YORK,10601,NaN,NaN,NaN,NaN,NaN,NaN
794,31 SHOREHAM DRIVE WEST,NaN,DIX HILLS,SEAN LEGUERNIC,NEW YORK,11746,SUFFOLK,100 BROOK AVE CORP.,3843173,31 SHOREHAM DR W,...,DIX HILLS,SEAN LEGUERNIC,NEW YORK,11746,NaN,NaN,NaN,NaN,NaN,NaN
807,NaN,NaN,NaN,NaN,NaN,NaN,WESTCHESTER,100 CARYL AVE. CORP.,1778965,2382 BOSTON POST ROAD,...,LARCHMONT,100 CARYL AVE. CORP.,NEW YORK,10538-1068,NaN,NaN,NaN,NaN,NaN,NaN
808,NaN,NaN,NaN,NaN,NaN,NaN,WESTCHESTER,100 CARYL AVE. REALTY CORP.,1783712,2382 BOSTON POST ROAD,...,LARCHMONT,100 CARYL AVE. REALTY CORP.,NEW YORK,10538-1068,NaN,NaN,NaN,NaN,NaN,NaN
812,522 ALICIA DRIVE,NaN,WESTBURY,CARMELLE BELLEFLEUR,NEW YORK,11590,KINGS,100 C.B. REALTY CORP.,1790672,522 ALICIA DRIVE,...,WESTBURY,100 C.B. REALTY CORP.,NEW YORK,11590,NaN,NaN,NaN,NaN,NaN,NaN
834,C/O FRE MANAGEMENT,60 OAK DR STE 3,SYOSSET,NICK BRATSAFOLIS,NEW YORK,11791,NASSAU,100 CLINTON AVENUE OWNERS CORP.,1058560,C/O FRE MANAGEMENT,...,SYOSSET,NICK BRATSAFOLIS,NEW YORK,11791,NaN,NaN,NaN,NaN,NaN,NaN
871,100 MAIN ST,NaN,SALAMANCA,DEMITRIOS KOLOKOURIS,NEW YORK,14779,LIVINGSTON,100 DEMETRIOS INC.,3746017,100 MAIN ST,...,SALAMANCA,100 DEMETRIOS INC.,NEW YORK,14779,NaN,NaN,NaN,NaN,NaN,NaN
906,"400 ALTON ROAD, APT. 2002",NaN,MIAMI BEACH,VITTORIO MARZOTTO,FLORIDA,33139,NEW YORK,100 ELEVENTH AVENUE # 8A INC.,4065408,509 MADISON AVE STE 1200,...,MIAMI BEACH,100 ELEVENTH AVENUE # 8A INC.,FLORIDA,33139,509 MADISON AVE STE 1206,NaN,NEW YORK,VALLA & ASSOCIATES INC PC,NEW YORK,10022
915,65 EAGLE LN,NaN,TAPPAN,HARRIET WAINLAND,NEW YORK,10983,KINGS,100 ELMWOOD REALTY CORP.,105508,GRAUBARD MILLER,...,LONG ISLAND CITY,CROSSTOWN MANAGEMENT,NEW YORK,11101,NaN,NaN,NaN,NaN,NaN,NaN
928,690 RIVIERA DR.,NaN,MASTIC BEACH,EVAGLEOS KANDIAS,NEW YORK,11951-7001,SUFFOLK,100 FATHOMS ENTERPRISES INC.,2469607,690 RIVIERA DR.,...,MASTIC BEACH,100 FATHOMS ENTERPRISES INC.,NEW YORK,11951-7001,NaN,NaN,NaN,NaN,NaN,NaN
946,100 FOX HILL DR,NaN,BAITING HOLLOW,NEIL REGO,NEW YORK,11933,SUFFOLK,100 FOX HILL CORP.,1164657,PATIO BLDG.,...,BAITING HOLLOW,100 FOX HILL CORP.,NEW YORK,11933,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
city_group.describe()

                 dos_id                                                     \
                  count          mean           std        min         25%
location_city
ALEXANDRIA BAY      1.0  1.692930e+06           NaN  1692930.0  1692930.00
ASTORIA             1.0  2.193682e+06           NaN  2193682.0  2193682.00
BAITING HOLLOW      1.0  1.164657e+06           NaN  1164657.0  1164657.00
BAYPORT             1.0  3.314005e+06           NaN  3314005.0  3314005.00
BAYSIDE             1.0  9.339830e+05           NaN   933983.0   933983.00
BREWSTER            1.0  2.571259e+06           NaN  2571259.0  2571259.00
BRONX               4.0  3.394273e+06  1.054467e+06  1823461.0  3327186.25
BROOKLYN           15.0  2.475003e+06  1.191289e+06   108714.0  1695267.00
CENTEREACH          1.0  2.331187e+06           NaN  2331187.0  2331187.00
CHITTENANGO         1.0  3.985227e+06           NaN  3985227.0  3985227.00
CLAYTON             1.0  1.947051e+06           NaN  1947051.0  1947051.00
CUMMING             1.0  2.116899e+06           NaN  2116899.0  2116899.00
DIX HILLS           1.0  3.843173e+06           NaN  3843173.0  3843173.00
EAST ELMHURST       1.0  4.297311e+06           NaN  4297311.0  4297311.00
ELMIRA              1.0  3.101753e+06           NaN  3101753.0  3101753.00
FARMINGDALE         1.0  4.222927e+06           NaN  4222927.0  4222927.00
FLUSHING            2.0  3.954844e+06  3.312322e+05  3720627.0  3837735.25
FOREST HILLS        1.0  4.215784e+06           NaN  4215784.0  4215784.00
FORT LEE            1.0  3.916029e+06           NaN  3916029.0  3916029.00
FRANKLIN SQUARE     1.0  2.577760e+06           NaN  2577760.0  2577760.00
FREEVILLE           1.0  3.547128e+06           NaN  3547128.0  3547128.00
FRESH MEADOWS       1.0  4.154481e+06           NaN  4154481.0  4154481.00
GREAT NECK          1.0  1.045005e+06           NaN  1045005.0  1045005.00
HEMPSTEAD           1.0  4.208221e+06           NaN  4208221.0  4208221.00
HOWARD BEACH        1.0  3.239056e+06           NaN  3239056.0  3239056.00
KINGS POINT         1.0  3.391009e+06           NaN  3391009.0  3391009.00
LARCHMONT           2.0  1.781338e+06  3.356636e+03  1778965.0  1780151.75
LONG ISLAND CITY    1.0  1.055080e+05           NaN   105508.0   105508.00
MASTIC BEACH        1.0  2.469607e+06           NaN  2469607.0  2469607.00
MIAMI BEACH         1.0  4.065408e+06           NaN  4065408.0  4065408.00
MT. VERNON          1.0  2.512637e+06           NaN  2512637.0  2512637.00
NEW YORK           20.0  2.439900e+06  1.488716e+06   108789.0   990196.50
NIAGARA FALLS       1.0  3.477685e+06           NaN  3477685.0  3477685.00
NORTH MERRICK       1.0  9.204440e+05           NaN   920444.0   920444.00
OGDENSBURG          1.0  1.256092e+06           NaN  1256092.0  1256092.00
OZONE PARK          1.0  2.115320e+06           NaN  2115320.0  2115320.00
PENFIELD            1.0  3.630800e+06           NaN  3630800.0  3630800.00
PORT JEFFERSON      1.0  2.995388e+06           NaN  2995388.0  2995388.00
POUND RIDGE         1.0  1.719211e+06           NaN  1719211.0  1719211.00
RICHMOND HILL       2.0  3.101298e+06  1.835265e+06  1803570.0  2452434.00
ROCHESTER           2.0  2.005102e+06  2.289686e+06   386049.0  1195575.25
ROCKAWAY PARK       1.0  2.396780e+06           NaN  2396780.0  2396780.00
ROCKVILLE CENTRE    1.0  4.163990e+06           NaN  4163990.0  4163990.00
ROSLYN HEIGHTS      1.0  2.664830e+06           NaN  2664830.0  2664830.00
RUTHERFORD          1.0  6.693800e+04           NaN    66938.0    66938.00
SALAMANCA           1.0  3.746017e+06           NaN  3746017.0  3746017.00
SCHENECTADY         1.0  3.735707e+06           NaN  3735707.0  3735707.00
SCOTIA              1.0  2.067108e+06           NaN  2067108.0  2067108.00
STATEN ISLAND       1.0  1.601758e+06           NaN  1601758.0  1601758.00
STONY CREEK         1.0  1.100715e+06           NaN  1100715.0  1100715.00
SYOSSET             1.0  1.058560e+06           NaN  1058560.0  1058560.00
SYRACUSE            1.0  3.965740e+06           NaN  3965740.0  3965740.00
WATERTOWN           1.0  2.001227e+06           NaN  2001227.0  2001227.00
WEST HEMPSTEAD      1.0  3.451085e+06           NaN  3451085.0  3451085.00
WESTBURY            1.0  1.790672e+06           NaN  1790672.0  1790672.00
WHITE PLAINS        1.0  2.317051e+06           NaN  2317051.0  2317051.00
WILLIAMSVILLE       1.0  3.474891e+06           NaN  3474891.0  3474891.00
WOODSIDE            1.0  3.553480e+05           NaN   355348.0   355348.00
YORKTOWN HTS        1.0  4.149752e+06           NaN  4149752.0  4149752.00


                        50%         75%        max
location_city
ALEXANDRIA BAY    1692930.0  1692930.00  1692930.0
ASTORIA           2193682.0  2193682.00  2193682.0
BAITING HOLLOW    1164657.0  1164657.00  1164657.0
BAYPORT           3314005.0  3314005.00  3314005.0
BAYSIDE            933983.0   933983.00   933983.0
BREWSTER          2571259.0  2571259.00  2571259.0
BRONX             3830551.0  3897638.00  4092530.0
BROOKLYN          2183633.0  3702509.00  3813470.0
CENTEREACH        2331187.0  2331187.00  2331187.0
CHITTENANGO       3985227.0  3985227.00  3985227.0
CLAYTON           1947051.0  1947051.00  1947051.0
CUMMING           2116899.0  2116899.00  2116899.0
DIX HILLS         3843173.0  3843173.00  3843173.0
EAST ELMHURST     4297311.0  4297311.00  4297311.0
ELMIRA            3101753.0  3101753.00  3101753.0
FARMINGDALE       4222927.0  4222927.00  4222927.0
FLUSHING          3954843.5  4071951.75  4189060.0
FOREST HILLS      4215784.0  4215784.00  4215784.0
FORT LEE          3916029.0  3916029.00  3916029.0
FRANKLIN SQUARE   2577760.0  2577760.00  2577760.0
FREEVILLE         3547128.0  3547128.00  3547128.0
FRESH MEADOWS     4154481.0  4154481.00  4154481.0
GREAT NECK        1045005.0  1045005.00  1045005.0
HEMPSTEAD         4208221.0  4208221.00  4208221.0
HOWARD BEACH      3239056.0  3239056.00  3239056.0
KINGS POINT       3391009.0  3391009.00  3391009.0
LARCHMONT         1781338.5  1782525.25  1783712.0
LONG ISLAND CITY   105508.0   105508.00   105508.0
MASTIC BEACH      2469607.0  2469607.00  2469607.0
MIAMI BEACH       4065408.0  4065408.00  4065408.0
MT. VERNON        2512637.0  2512637.00  2512637.0
NEW YORK          2369252.0  3664428.50  4748537.0
NIAGARA FALLS     3477685.0  3477685.00  3477685.0
NORTH MERRICK      920444.0   920444.00   920444.0
OGDENSBURG        1256092.0  1256092.00  1256092.0
OZONE PARK        2115320.0  2115320.00  2115320.0
PENFIELD          3630800.0  3630800.00  3630800.0
PORT JEFFERSON    2995388.0  2995388.00  2995388.0
POUND RIDGE       1719211.0  1719211.00  1719211.0
RICHMOND HILL     3101298.0  3750162.00  4399026.0
ROCHESTER         2005101.5  2814627.75  3624154.0
ROCKAWAY PARK     2396780.0  2396780.00  2396780.0
ROCKVILLE CENTRE  4163990.0  4163990.00  4163990.0
ROSLYN HEIGHTS    2664830.0  2664830.00  2664830.0
RUTHERFORD          66938.0    66938.00    66938.0
SALAMANCA         3746017.0  3746017.00  3746017.0
SCHENECTADY       3735707.0  3735707.00  3735707.0
SCOTIA            2067108.0  2067108.00  2067108.0
STATEN ISLAND     1601758.0  1601758.00  1601758.0
STONY CREEK       1100715.0  1100715.00  1100715.0
SYOSSET           1058560.0  1058560.00  1058560.0
SYRACUSE          3965740.0  3965740.00  3965740.0
WATERTOWN         2001227.0  2001227.00  2001227.0
WEST HEMPSTEAD    3451085.0  3451085.00  3451085.0
WESTBURY          1790672.0  1790672.00  1790672.0
WHITE PLAINS      2317051.0  2317051.00  2317051.0
WILLIAMSVILLE     3474891.0  3474891.00  3474891.0
WOODSIDE           355348.0   355348.00   355348.0
YORKTOWN HTS      4149752.0  4149752.00  4149752.0

__question__ shouldn't this have given me the number of corporations in each city? also how are there so few cities given that there are many more in NYS (and 99 in the corp describe?)

In [12]:
city_group.count('kings')

TypeError: count() takes 1 positional argument but 2 were given

In [13]:
corp.count('kings')

NameError: name 'corp' is not defined

__question__ why is 'corp' not defined, when that's the name of the dataframe that i am pulling data from?

In [14]:
corps.min(initial_dos_filing_date)

NameError: name 'initial_dos_filing_date' is not defined

__question__ it looks like all of my data is objects, maybe that is my problem? would i need to convert it either to strings in order to group etc?